name: Release Build

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags -f

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.6'

      # docker `golang-cross` image cache
      # `cache-go-cross-v1-16-6`
      - run: mkdir -p ~/docker-cache
      - name: docker image cache
        id: cache-go-cross-v1-16-6
        uses: actions/cache@v2
        with:
          path: ~/docker-cache
          # Adjust key to meet your cache time requirements e.g.
          # ${{ hashFiles(*) }} can be useful here to invalidate
          # cache on file changes
          key: cache-go-cross-v1-16-6

      - if: steps.cache-go-cross-v1-16-6.outputs.cache-hit != 'true'
        run: |
          docker pull troian/golang-cross:v1.16.6
          docker save -o ~/docker-cache/golang-cross.tar troian/golang-cross:v1.16.6

      - if: steps.cache-go-cross-v1-16-6.outputs.cache-hit == 'true'
        run: docker load -i ~/docker-cache/golang-cross.tar

      # build
      - name: setup release environment
        run: |-
          cp artalk-go.example.yml artalk-go.yml
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' > .release-env

      - name: build and release publish
        run: make release
